// Package shadowrocket contains the small, deliberately one-way macOS bridge
// used by the HITSZ profile. Shadowrocket owns the proxy protocol (including
// AnyTLS); zju-connect never handles a node secret after handing it to macOS.
package shadowrocket

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/netip"
	"net/url"
	"os"
	"os/exec"
	"runtime"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/net/publicsuffix"
)

const bundleID = "com.liguangming.Shadowrocket"

var ErrUnsupported = errors.New("Shadowrocket integration is only supported on macOS")

type Controller struct {
	open func(context.Context, ...string) error
}

func New() Controller { return Controller{open: openWithSystem} }
func openWithSystem(ctx context.Context, args ...string) error {
	return exec.CommandContext(ctx, "open", args...).Run()
}

// Apply waits for macOS to accept each URL. Shadowrocket exposes no reliable
// public packet-tunnel status callback, so this intentionally does not claim
// that an outbound tunnel has already been established.
func (c Controller) Apply(ctx context.Context, action, nodeFile string, updateSubscriptions bool) error {
	if action == "" {
		action = "off"
	}
	if action != "off" || nodeFile != "" || updateSubscriptions {
		if runtime.GOOS != "darwin" {
			return ErrUnsupported
		}
	}
	if nodeFile != "" {
		node, err := ReadAnyTLSNodeFile(nodeFile)
		if err != nil {
			return err
		}
		if err := c.open(ctx, "-g", "-b", bundleID, node); err != nil {
			return fmt.Errorf("import AnyTLS node in Shadowrocket: %w", err)
		}
	}
	if updateSubscriptions {
		if err := c.open(ctx, "-g", "shadowrocket://update-subs"); err != nil {
			return fmt.Errorf("update Shadowrocket subscriptions: %w", err)
		}
	}
	switch action {
	case "off":
		return nil
	case "open":
		return c.open(ctx, "-g", "-b", bundleID)
	case "connect":
		if err := c.open(ctx, "-g", "-b", bundleID); err != nil {
			return fmt.Errorf("open Shadowrocket: %w", err)
		}
		if err := c.open(ctx, "-g", "shadowrocket://connect"); err != nil {
			return fmt.Errorf("connect Shadowrocket: %w", err)
		}
		return nil
	default:
		return fmt.Errorf("unsupported Shadowrocket action %q (want off, open, or connect)", action)
	}
}

func (c Controller) Disconnect(ctx context.Context) error {
	if runtime.GOOS != "darwin" {
		return ErrUnsupported
	}
	return c.open(ctx, "-g", "shadowrocket://disconnect")
}

func ReadAnyTLSNodeFile(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	node := strings.TrimSpace(string(data))
	if strings.ContainsAny(node, "\r\n") {
		return "", errors.New("AnyTLS node file must contain exactly one URI")
	}
	if err := ValidateAnyTLSURI(node); err != nil {
		return "", err
	}
	return node, nil
}

func ValidateAnyTLSURI(raw string) error {
	u, err := url.ParseRequestURI(raw)
	if err != nil {
		return fmt.Errorf("invalid AnyTLS URI: %w", err)
	}
	if !strings.EqualFold(u.Scheme, "anytls") || u.Hostname() == "" || u.Port() == "" {
		return errors.New("invalid AnyTLS URI: require anytls://host:port")
	}
	return nil
}

func ConfigFragment(relayAddr string) string {
	return "# Generated by HITSZ Connect; merge these entries into the active Shadowrocket config.\n" +
		"[General]\n" +
		"always-real-ip = *\n\n" +
		"[Host]\n" +
		"hitsz.edu.cn = server:udp://" + relayAddr + "\n" +
		"*.hitsz.edu.cn = server:udp://" + relayAddr + "\n"
}

// HITSZConfigFragment returns the Shadowrocket entries needed to send HITSZ
// resources through zju-connect's local SOCKS5 server. The caller can append
// the returned sections to an existing Shadowrocket configuration.
//
// CIDRs are deliberately restricted to the three HITSZ campus ranges supplied
// by the user: 10.248.0.0/16 through 10.250.0.0/16. This prevents an
// untrusted or malformed resource list from installing a catch-all, LAN,
// loopback, multicast, public-Internet, or unrelated private-network rule in
// Shadowrocket. Invalid inputs are omitted so the function remains convenient
// for callers handling a partly valid resource list.
func HITSZConfigFragment(relayAddr, socksBind string, ipv4CIDRs, domains []string) string {
	relayAddr = normalizedRelayAddr(relayAddr)
	socksPort := localPort(socksBind, "1080")
	domains = normalizedDomains(domains)
	ipv4CIDRs = normalizedHITSZCampusIPv4CIDRs(ipv4CIDRs)

	var fragment strings.Builder
	fragment.WriteString("# Generated by HITSZ Connect; merge these entries into the active Shadowrocket config.\n")
	fragment.WriteString("[General]\n")
	fragment.WriteString("always-real-ip = *\n\n")
	fragment.WriteString("[Proxy]\n")
	fmt.Fprintf(&fragment, "HITSZ-aTrust = socks5,127.0.0.1,%s\n\n", socksPort)
	fragment.WriteString("[Rule]\n")
	fragment.WriteString("# Dynamic IP rules are restricted to 10.248.0.0/16 through 10.250.0.0/16.\n")
	for _, domain := range domains {
		fmt.Fprintf(&fragment, "DOMAIN-SUFFIX,%s,HITSZ-aTrust\n", domain)
	}
	for _, cidr := range ipv4CIDRs {
		fmt.Fprintf(&fragment, "IP-CIDR,%s,HITSZ-aTrust,no-resolve\n", cidr)
	}
	fragment.WriteString("\n[Host]\n")
	fmt.Fprintf(&fragment, "hitsz.edu.cn = server:udp://%s\n", relayAddr)
	fmt.Fprintf(&fragment, "*.hitsz.edu.cn = server:udp://%s\n", relayAddr)

	return fragment.String()
}

func normalizedRelayAddr(bind string) string {
	const fallback = "127.0.0.1:53535"
	bind = strings.TrimSpace(bind)
	if bind == "" {
		return fallback
	}

	host, port, err := splitBindAddr(bind)
	if err != nil {
		return fallback
	}
	if host == "" || strings.EqualFold(host, "localhost") {
		return "127.0.0.1:" + port
	}

	addr, err := netip.ParseAddr(host)
	if err != nil || (!addr.IsLoopback() && !addr.IsUnspecified()) {
		return fallback
	}
	if addr.IsUnspecified() {
		return "127.0.0.1:" + port
	}
	if addr.Is4() {
		return addr.String() + ":" + port
	}
	return "[" + addr.String() + "]:" + port
}

func localPort(bind, fallback string) string {
	bind = strings.TrimSpace(bind)
	if bind == "" {
		return fallback
	}
	_, port, err := splitBindAddr(bind)
	if err != nil {
		return fallback
	}
	return port
}

func splitBindAddr(bind string) (host, port string, err error) {
	host, port, err = net.SplitHostPort(bind)
	if err != nil {
		return "", "", err
	}
	portNumber, err := strconv.ParseUint(port, 10, 16)
	if err != nil || portNumber == 0 {
		return "", "", errors.New("invalid port")
	}
	return host, strconv.FormatUint(portNumber, 10), nil
}

func normalizedDomains(inputs []string) []string {
	seen := make(map[string]struct{}, len(inputs))
	for _, input := range inputs {
		if domain := normalizedDomain(input); domain != "" {
			seen[domain] = struct{}{}
		}
	}

	domains := make([]string, 0, len(seen))
	for domain := range seen {
		domains = append(domains, domain)
	}
	sort.Strings(domains)
	return domains
}

func normalizedDomain(input string) string {
	domain := strings.ToLower(strings.TrimSpace(input))
	domain = strings.TrimRight(domain, ".")
	if strings.HasPrefix(domain, "*.") {
		domain = domain[2:]
	} else if strings.HasPrefix(domain, ".") {
		domain = domain[1:]
	}
	if domain == "" || len(domain) > 253 {
		return ""
	}
	if _, err := netip.ParseAddr(domain); err == nil {
		return ""
	}
	if !strings.Contains(domain, ".") {
		return ""
	}

	for _, label := range strings.Split(domain, ".") {
		if !validDomainLabel(label) {
			return ""
		}
	}
	if suffix, icann := publicsuffix.PublicSuffix(domain); icann && suffix == domain {
		return ""
	}
	return domain
}

func validDomainLabel(label string) bool {
	if len(label) == 0 || len(label) > 63 || label[0] == '-' || label[len(label)-1] == '-' {
		return false
	}
	for _, char := range []byte(label) {
		if (char >= 'a' && char <= 'z') || (char >= '0' && char <= '9') || char == '-' {
			continue
		}
		return false
	}
	return true
}

func normalizedHITSZCampusIPv4CIDRs(inputs []string) []string {
	seen := make(map[netip.Prefix]struct{}, len(inputs))
	for _, input := range inputs {
		prefix, err := netip.ParsePrefix(strings.TrimSpace(input))
		if err != nil || !prefix.Addr().Is4() {
			continue
		}
		prefix = prefix.Masked()
		if !safeHITSZCampusIPv4Prefix(prefix) {
			continue
		}
		seen[prefix] = struct{}{}
	}

	prefixes := minimizedHITSZCampusPrefixes(seen)
	sort.Slice(prefixes, func(i, j int) bool {
		if prefixes[i].Addr() != prefixes[j].Addr() {
			return prefixes[i].Addr().Less(prefixes[j].Addr())
		}
		return prefixes[i].Bits() < prefixes[j].Bits()
	})

	cidrs := make([]string, len(prefixes))
	for i, prefix := range prefixes {
		cidrs[i] = prefix.String()
	}
	return cidrs
}

// minimizedHITSZCampusPrefixes removes prefixes already covered by a parent
// and combines complete sibling pairs whenever doing so remains inside the
// explicitly allowed HITSZ ranges. It keeps generated configurations compact
// without widening any route.
func minimizedHITSZCampusPrefixes(prefixes map[netip.Prefix]struct{}) []netip.Prefix {
	for prefix := range prefixes {
		for parent := range prefixes {
			if parent != prefix && parent.Bits() < prefix.Bits() && parent.Contains(prefix.Addr()) {
				delete(prefixes, prefix)
				break
			}
		}
	}

	for {
		parents := make(map[netip.Prefix][]netip.Prefix, len(prefixes))
		for prefix := range prefixes {
			if prefix.Bits() == 0 {
				continue
			}
			parent := netip.PrefixFrom(prefix.Addr(), prefix.Bits()-1).Masked()
			if safeHITSZCampusIPv4Prefix(parent) {
				parents[parent] = append(parents[parent], prefix)
			}
		}

		merged := false
		for parent, children := range parents {
			if len(children) != 2 {
				continue
			}
			delete(prefixes, children[0])
			delete(prefixes, children[1])
			prefixes[parent] = struct{}{}
			merged = true
		}
		if !merged {
			break
		}
	}

	result := make([]netip.Prefix, 0, len(prefixes))
	for prefix := range prefixes {
		result = append(result, prefix)
	}
	return result
}

const (
	hitszCampusStart uint32 = 0x0af80000 // 10.248.0.0
	hitszCampusEnd   uint32 = 0x0afaffff // 10.250.255.255
)

func safeHITSZCampusIPv4Prefix(prefix netip.Prefix) bool {
	if !prefix.IsValid() || !prefix.Addr().Is4() {
		return false
	}

	addr := prefix.Masked().Addr().As4()
	start := uint32(addr[0])<<24 | uint32(addr[1])<<16 | uint32(addr[2])<<8 | uint32(addr[3])
	size := uint64(1) << (32 - prefix.Bits())
	end := uint64(start) + size - 1
	return start >= hitszCampusStart && end <= uint64(hitszCampusEnd)
}
